# Generated by Django 3.0.6 on 2020-08-29 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_userprofile_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile_new',
            name='state',
        ),
    ]
