# Generated by Django 3.0.6 on 2020-08-29 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_remove_userprofile_new_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile_new',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
