# Generated by Django 3.0.6 on 2020-08-30 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mysite', '0007_historicaluserprofile_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher_uses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_to', models.EmailField(blank=True, max_length=254, null=True)),
                ('used_date', models.DateField(blank=True, null=True)),
                ('used_time', models.TimeField(blank=True, null=True)),
                ('Voucher_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Voucher')),
                ('used_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
