# Generated by Django 3.0.6 on 2020-08-30 10:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_voucher_uses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher_uses',
            name='used_date',
        ),
        migrations.RemoveField(
            model_name='voucher_uses',
            name='used_time',
        ),
        migrations.AddField(
            model_name='voucher_uses',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='voucher_uses',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='voucher_uses',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
